#!/bin/sh
# Launch Desktop Application from a terminal in X Server / Wayland session
# Example/integration test:
# ./gui mousepad $HOME/.profile
# ./gui `which mousepad` $HOME/.profile
setsid "${@}" >> "${HOME}/gui-$(basename ${1}).log" 2>&1 &
