#!/bin/sh

closure() {
    # llama-cli -hf unsloth/gpt-oss-20b-GGUF:Q4_0
    # llama-cli -hf mistralai/Ministral-3-3B-Instruct-2512-GGUF:Q4_K_M
    local THREAD_CNT=6
    local CMD_LINE="llama-server --threads ${THREAD_CNT} --offline --host 0.0.0.0 --port 11434 --jinja --no-warmup --flash-attn on --batch-size 512 --ubatch-size 512 --ctx-size 4096 --n-gpu-layers 16"
    eval ${CMD_LINE}
}

closure
