#!/bin/sh

closure() {
    # llama-cli -hf unsloth/gpt-oss-20b-GGUF:Q4_0
    local THREAD_CNT=6
    local CMD_LINE="llama-server --threads ${THREAD_CNT} --offline --host 0.0.0.0 --port 11434 --jinja --no-warmup --batch-size 512 --ubatch-size 512 --ctx-size 4096 --n-gpu-layers 16"
    eval ${CMD_LINE}
}

closure
