#!/bin/sh

closure() {
    # llama-cli -hf google/gemma-4-E4B-it-qat-q4_0-gguf:Q4_0
    # llama-cli -hf unsloth/gpt-oss-20b-GGUF:Q8_0
    local THREAD_CNT=6
    local CMD_LINE="llama-server --threads ${THREAD_CNT} --offline --host 0.0.0.0 --port 11434 --jinja --no-warmup --batch-size 512 --ubatch-size 512 --ctx-size 8192 --n-gpu-layers 0 --no-kv-offload --no-op-offload --no-mmproj-offload"
    eval ${CMD_LINE}
}

closure
