#!/bin/sh

# ollama list
# ollama pull hf.co/google/gemma-4-E4B-it-qat-q4_0-gguf
# ollama pull hf.co/Qwen/Qwen3-4B-GGUF:Q4_K_M
# ollama pull hf.co/unsloth/gpt-oss-20b-GGUF:Q4_0
# ollama pull hf.co/mistralai/Ministral-3-3B-Instruct-2512-GGUF:Q4_K_M
# rm -rf ~/.ollama/models/blobs/*partial*
# ollama launch pi
# ollama launch opencode

closure() {
    export OLLAMA_VULKAN=0

    export OLLAMA_CONTEXT_LENGTH=16384
    export OLLAMA_MAX_LOADED_MODELS=1
    export OLLAMA_FLASH_ATTENTION=1
    export OLLAMA_HOST=0.0.0.0:11434
    ollama serve
}

closure
